%%%-------------------------------------------------------------------
%%% @author heyoka
%%% @copyright (C) 2020, <COMPANY>
%%% @doc
%%%
%%% @end
%%% Created : 20. Feb 2020 09:10
%%%-------------------------------------------------------------------
-module(dfs_test).
-author("heyoka").
%% API
-export([]).

-ifdef(TEST).
-include_lib("eunit/include/eunit.hrl").

override_test() ->
   Replacements = [
      {<<"number1">>, 22.78897},
      {<<"number2">>, -3.14},
      {<<"number3">>, -556595895},
      {<<"string1">>, <<"this is my string">>},
      {<<"string2">>, <<"string2">>},
      {<<"text1">>, <<"This is my text !">>},
      {<<"dur1">>, <<"33s">>},
      {<<"dur2">>, <<"12h">>},
      {<<"lambda1">>, <<"lambda: \"answer\" != (42 * 1)">>}

   ],
   {NewDFS, ParseResult} = dfs:parse_file("test/override.dfs", [], Replacements),
   {ok, DFSOut} = file:read_file("test/override_result.dfs"),
   ?assertEqual(binary_to_list(DFSOut), NewDFS),
   ExpectedResult =
      {[{{<<"eval">>,1},
         [{lambda,"Answer /= (42 * 1)",[<<"answer">>],["Answer"]}],
         [{<<"add">>,[{int,-3.14}]},
            {<<"message">>,[{text,<<"This is my text !">>}]},
            {<<"timeouts">>,[{duration,<<"33s">>}]},
            {<<"after">>,[{duration,<<"12h">>}]}]}],
         []},
   ?assertEqual(ExpectedResult, ParseResult).

macro_test() ->
   FileName = "test/macro1.dfs",
   StringData1 = test_helper:string_data("test/ctc_module_condition.dfs"),
   StringData2 = test_helper:string_data("test/publish_macro.dfs"),

   {_, Res} = dfs:parse_file(FileName, [], [],
      [{<<"ctc_module_condition">>, StringData1}, {<<"publish_macro">>, StringData2}]),
   Expected =
      {[{{<<"case">>,2},
         [{lambda,"Data_State_Err == 1 orelse Data_State_Warn == 1",
            [<<"data.State.Err">>,<<"data.State.Warn">>],
            ["Data_State_Err","Data_State_Warn"]},
            {lambda,"Data_State_Auto == 1",
               [<<"data.State.Auto">>],
               ["Data_State_Auto"]}],
         [{<<"values">>,[{string,<<"Err">>},{string,<<"Ok">>}]},
            {<<"as">>,[{string,<<"data.condition">>}]},
            {<<"default">>,[{string,<<"Warn">>}]}]},
         {{<<"s7read">>,3},
            [],
            [{<<"vars">>,
               [{string,<<"DB12.DBX0.0">>},
                  {string,<<"DB12.DBX0.1">>},
                  {string,<<"DB12.DBX0.2">>},
                  {string,<<"DB12.DBX0.3">>}]},
               {<<"as">>,
                  [{string,<<"data.State.Err">>},
                     {string,<<"data.State.Warn">>},
                     {string,<<"data.State.Auto">>},
                     {string,<<"data.State.AutoRdy">>}]}]},
         {{<<"debug">>,5},[],[]},
         {{<<"where">>,6},
            [{lambda,"Val > 2",[<<"val">>],["Val"]}],
            []},
         {{<<"keep">>,7},[],[{<<"fields">>,[{string,<<"val">>}]}]},
         {{<<"set">>,8},
            [],
            [{<<"fields">>,[{string,<<"id">>}]},
               {<<"field_values">>,[{string,<<"myid222">>}]}]},
         {{<<"delete">>,10},
            [],
            [{<<"fields">>,
               [{string,<<"val">>},{string,<<"some stringy">>}]},
               {<<"max">>,[{int,23}]}]},
         {{<<"default">>,11},
            [],
            [{<<"fields">>,[{string,<<"id">>}]},
               {<<"field_values">>,[{string,<<"myid222">>}]}]}],
         [{{<<"delete">>,10},{<<"set">>,8}},
            {{<<"set">>,8},{<<"keep">>,7}},
            {{<<"keep">>,7},{<<"where">>,6}},
            {{<<"default">>,11},{<<"delete">>,10}},
            {{<<"s7read">>,3},{<<"case">>,2}},
            {{<<"where">>,6},{<<"s7read">>,3}},
            {{<<"debug">>,5},{<<"default">>,11}}]},

   ?assertEqual(Expected, Res).



macro_2_test() ->
   FileName = "src/CTC_CM_ConvAccKDR_111107.dfs",
   MacroData = test_helper:string_data("src/macroFB1650_ConvAccKDR.dfs"),

   {_, Res} = dfs:parse_file(FileName, [], [],
      [{<<"macroFB1650_ConvAccKDR">>, MacroData}]),

   Expected =
      {[{{<<"s7read">>,13},
         [],
         [{<<"ip">>,[{string,<<"192.168.121.201">>}]},
            {<<"rack">>,[{int,0}]},
            {<<"slot">>,[{int,1}]},
            {<<"every">>,[{duration,<<"200ms">>}]},
            {<<"align">>,[]},
            {<<"vars">>,
               [{string,<<"DB11107.DBX30.0">>},
                  {string,<<"DB11107.DBX30.1">>},
                  {string,<<"DB11107.DBX30.2">>},
                  {string,<<"DB11107.DBX30.3">>},
                  {string,<<"DB11107.DBX30.4">>},
                  {string,<<"DB11107.DBX30.5">>},
                  {string,<<"DB11107.DBX30.6">>},
                  {string,<<"DB11107.DBX30.7">>},
                  {string,<<"DB11107.DBX31.0">>},
                  {string,<<"DB11107.DBX31.1">>},
                  {string,<<"DB11107.DBW48">>},
                  {string,<<"DB11107.DBW50">>},
                  {string,<<"DB11107.DBW52">>},
                  {string,<<"DB11107.DBX0.0">>},
                  {string,<<"DB11107.DBX0.2">>},
                  {string,<<"DB11107.DBX0.3">>},
                  {string,<<"DB11107.DBX0.4">>},
                  {string,<<"DB11107.DBX0.5">>},
                  {string,<<"DB11107.DBX0.6">>},
                  {string,<<"DB11107.DBW2">>},
                  {string,<<"DB11107.DBD4">>},
                  {string,<<"DB11107.DBW8">>},
                  {string,<<"DB11107.DBW10">>},
                  {string,<<"DB11107.DBD32">>},
                  {string,<<"DB11107.DBD36">>},
                  {string,<<"DB11107.DBD40">>},
                  {string,<<"DB11107.DBD44">>}]},
            {<<"as">>,
               [{string,<<"data.DcrgZo1Occ">>},
                  {string,<<"data.DcrgZo2Occ">>},
                  {string,<<"data.ChZZo2Occ">>},
                  {string,<<"data.GapChkRear">>},
                  {string,<<"data.MtSw">>},
                  {string,<<"data.CcRdy">>},
                  {string,<<"data.DcrgZo1">>},
                  {string,<<"data.DcrgZo2">>},
                  {string,<<"data.TrspFrontP2toP1">>},
                  {string,<<"data.TrspFront">>},
                  {string,<<"data.Vel">>},
                  {string,<<"data.Acc">>},
                  {string,<<"data.Fill">>},
                  {string,<<"data.State.Err">>},
                  {string,<<"data.State.Off">>},
                  {string,<<"data.State.Manual">>},
                  {string,<<"data.State.Msg">>},
                  {string,<<"data.State.Auto">>},
                  {string,<<"data.State.AutoRdy">>},
                  {string,<<"data.Module.VerNo">>},
                  {string,<<"data.Module.ModNo">>},
                  {string,<<"data.Module.ModType">>},
                  {string,<<"data.Module.LacNo">>},
                  {string,<<"data.OpHrRet">>},
                  {string,<<"data.OpHr">>},
                  {string,<<"data.CycCntRet">>},
                  {string,<<"data.CycCnt">>}]}]},
         {{<<"where">>,14},
            [{lambda,"Data_State_Msg == 0 andalso Data_State_Err == 0",
               [<<"data.State.Err">>,<<"data.State.Msg">>],
               ["Data_State_Err","Data_State_Msg"]}],
            []},
         {{<<"change_detect">>,15},
            [],
            [{<<"timeout">>,[{duration,<<"30s">>}]}]},
         {{<<"where">>,16},
            [{lambda,"Data_State_Msg == 1 orelse Data_State_Err == 1",
               [<<"data.State.Err">>,<<"data.State.Msg">>],
               ["Data_State_Err","Data_State_Msg"]}],
            []},
         {{<<"s7read">>,17},
            [],
            [{<<"ip">>,[{string,<<"192.168.121.201">>}]},
               {<<"rack">>,[{int,0}]},
               {<<"slot">>,[{int,1}]},
               {<<"byte_offset">>,[{int,736}]},
               {<<"merge_field">>,[{string,<<"data">>}]},
               {<<"vars">>,
                  [{string,<<"DB2077.DBX0.3">>},
                     {string,<<"DB2077.DBX1.0">>},
                     {string,<<"DB2077.DBX1.1">>},
                     {string,<<"DB2077.DBX1.2">>},
                     {string,<<"DB2077.DBX1.3">>},
                     {string,<<"DB2077.DBX1.4">>},
                     {string,<<"DB2077.DBX1.5">>},
                     {string,<<"DB2077.DBX1.6">>},
                     {string,<<"DB2077.DBX1.7">>},
                     {string,<<"DB2077.DBX2.5">>},
                     {string,<<"DB2077.DBX3.7">>}]},
               {<<"as">>,
                  [{string,<<"data.alarm.CcNotRdy">>},
                     {string,<<"data.alarm.DrvInop">>},
                     {string,<<"data.alarm.TiOutStopFro">>},
                     {string,<<"data.alarm.TiOutTrsp">>},
                     {string,<<"data.alarm.TiOutDrv">>},
                     {string,<<"data.alarm.GapChkErr">>},
                     {string,<<"data.alarm.KdrFuncErr">>},
                     {string,<<"data.alarm.TiOutOcc">>},
                     {string,<<"data.alarm.TiOutExtLb">>},
                     {string,<<"data.alarm.TiOutReqOff">>},
                     {string,<<"data.alarm.SrvMod">>}]}]},
         {{<<"s7read">>,18},
            [],
            [{<<"ip">>,[{string,<<"192.168.121.201">>}]},
               {<<"rack">>,[{int,0}]},
               {<<"slot">>,[{int,1}]},
               {<<"byte_offset">>,[{int,736}]},
               {<<"merge_field">>,[{string,<<"data">>}]},
               {<<"vars">>,
                  [{string,<<"DB2077.DBX3.1">>},
                     {string,<<"DB2077.DBX3.2">>},
                     {string,<<"DB2077.DBX3.3">>},
                     {string,<<"DB2077.DBX3.4">>},
                     {string,<<"DB2077.DBX3.5">>},
                     {string,<<"DB2077.DBX3.6">>},
                     {string,<<"DB2077.DBW4">>},
                     {string,<<"DB2077.DBW6">>},
                     {string,<<"DB2077.DBW8">>},
                     {string,<<"DB2077.DBW10">>},
                     {string,<<"DB2077.DBW12">>},
                     {string,<<"DB2077.DBW14">>},
                     {string,<<"DB2077.DBW16">>},
                     {string,<<"DB2077.DBW18">>},
                     {string,<<"DB2077.DBW20">>},
                     {string,<<"DB2077.DBW22">>},
                     {string,<<"DB2077.DBW24">>},
                     {string,<<"DB2077.DBW26">>},
                     {string,<<"DB2077.DBW28">>}]},
               {<<"as">>,
                  [{string,<<"data.alarm.KdrMc1">>},
                     {string,<<"data.alarm.KdrMc2">>},
                     {string,<<"data.alarm.KdrMc3">>},
                     {string,<<"data.alarm.KdrMc4">>},
                     {string,<<"data.alarm.KdrMc5">>},
                     {string,<<"data.alarm.KdrMc6">>},
                     {string,<<"data.alarm.KdrCcNo">>},
                     {string,<<"data.alarm.Kdr.McNo1">>},
                     {string,<<"data.alarm.Kdr.ErrCode1">>},
                     {string,<<"data.alarm.Kdr.McNo2">>},
                     {string,<<"data.alarm.Kdr.ErrCode2">>},
                     {string,<<"data.alarm.Kdr.McNo3">>},
                     {string,<<"data.alarm.Kdr.ErrCode3">>},
                     {string,<<"data.alarm.Kdr.McNo4">>},
                     {string,<<"data.alarm.Kdr.ErrCode4">>},
                     {string,<<"data.alarm.Kdr.McNo5">>},
                     {string,<<"data.alarm.Kdr.ErrCode5">>},
                     {string,<<"data.alarm.Kdr.McNo6">>},
                     {string,<<"data.alarm.Kdr.ErrCode6">>}]}]},
         {{<<"change_detect">>,19},
            [],
            [{<<"timeout">>,[{duration,<<"30s">>}]}]},
         {{<<"union">>,20},[{connect,{<<"change_detect">>,19}}],[]},
         {{<<"set">>,21},
            [],
            [{<<"fields">>,[{string,<<"df">>},{string,<<"id">>}]},
               {<<"field_values">>,
                  [{string,<<"07.005">>},
                     {string,<<"CTC_CM_ConvAccKDR">>}]}]},
         {{<<"batch">>,22},
            [{int,5}],
            [{<<"timeout">>,[{duration,<<"10s">>}]}]},
         {{<<"crate_out">>,23},
            [],
            [{<<"table">>,[{string,<<"teckdr">>}]},
               {<<"db_fields">>,
                  [{string,<<"id">>},
                     {string,<<"df">>},
                     {string,<<"data_obj">>}]},
               {<<"faxe_fields">>,
                  [{string,<<"id">>},
                     {string,<<"df">>},
                     {string,<<"data">>}]}]},
         {{<<"mqtt_publish">>,24},
            [],
            [{<<"topic">>,
               [{string,<<"ttgw/data/ctc/convacckdr/111107">>}]}]},
         {{<<"http_post_crate">>,25},
            [],
            [{<<"table">>,[{string,<<"tec_kdrerr">>}]},
               {<<"db_fields">>,
                  [{string,<<"id">>},
                     {string,<<"df">>},
                     {string,<<"data_obj">>}]},
               {<<"faxe_fields">>,
                  [{string,<<"id">>},
                     {string,<<"df">>},
                     {string,<<"data">>}]}]}],
         [{{<<"http_post_crate">>,25},{<<"mqtt_publish">>,24}},
            {{<<"mqtt_publish">>,24},{<<"set">>,21}},
            {{<<"crate_out">>,23},{<<"batch">>,22}},
            {{<<"batch">>,22},{<<"set">>,21}},
            {{<<"set">>,21},{<<"union">>,20}},
            {{<<"union">>,20},{<<"change_detect">>,15}},
            {{<<"change_detect">>,19},{<<"s7read">>,18}},
            {{<<"s7read">>,18},{<<"s7read">>,17}},
            {{<<"s7read">>,17},{<<"where">>,16}},
            {{<<"where">>,16},{<<"s7read">>,13}},
            {{<<"change_detect">>,15},{<<"where">>,14}},
            {{<<"where">>,14},{<<"s7read">>,13}}]}
   ,

   ?assertEqual(Expected, Res).



-endif.


