-file("/opt/erlang/19_1/lib/parsetools-2.1.3/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(dfs_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("apps/dfs/src/dfs_lexer.xrl", 52).

-export([reserved_word/1]).

reserved_word('var') -> true.

strip(TokenChars,TokenLen) -> lists:sublist(TokenChars, 2, TokenLen - 2).
strip_ref(TokenChars,TokenLen) -> lists:sublist(TokenChars, 3, TokenLen - 3).
unquote(TokenChars) -> binary:replace(list_to_binary(TokenChars),<<"\"">>, <<>>, [global]).
prep_regex(TokenChars) -> binary:replace(list_to_binary(TokenChars),<<"?">>, <<>>, [global]).
-file("/opt/erlang/19_1/lib/parsetools-2.1.3/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,_L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L0, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L0, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L0, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("apps/dfs/src/dfs_lexer.erl", 293).
yystate() -> 68.

yystate(75, [32|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 5, Tlen);
yystate(75, [9|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 5, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,75};
yystate(74, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(73, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 42, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 91, C =< 94 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 123, C =< 125 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,73};
yystate(72, [37|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 20, Tlen);
yystate(72, [10|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line+1, Tlen+1, 20, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(72, Ics, Line, Tlen+1, 20, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(72, Ics, Line, Tlen+1, 20, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 36 ->
    yystate(72, Ics, Line, Tlen+1, 20, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 38 ->
    yystate(72, Ics, Line, Tlen+1, 20, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,72};
yystate(71, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 42, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 91, C =< 94 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(71, [C|Ics], Line, Tlen, Action, Alen) when C >= 123, C =< 125 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(71, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,71};
yystate(70, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,70};
yystate(69, [102|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,69};
yystate(68, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [106|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [107|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [70|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line+1, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 32 ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 99 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 109, C =< 113 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 119, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(68, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,68};
yystate(67, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(67, [58|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 9, Tlen);
yystate(67, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,67};
yystate(66, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(66, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,66};
yystate(65, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 42, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 91, C =< 94 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 123, C =< 125 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(65, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,65};
yystate(64, [37|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 20, Tlen);
yystate(64, [10|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line+1, Tlen+1, 20, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(64, Ics, Line, Tlen+1, 20, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(64, Ics, Line, Tlen+1, 20, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,64};
yystate(63, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 42, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 91, C =< 94 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(63, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,63};
yystate(62, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(62, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,62};
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 0, Tlen);
yystate(61, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 0, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 0, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 0, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 0, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,61};
yystate(60, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(59, [97|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,59};
yystate(58, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(56, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(55, [51|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 42, C =< 50 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [C|Ics], Line, Tlen, Action, Alen) when C >= 52, C =< 126 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,54};
yystate(53, [97|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 9, Tlen);
yystate(53, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(53, [65|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 9, Tlen);
yystate(53, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,53};
yystate(52, [97|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,52};
yystate(51, [100|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,51};
yystate(50, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(50, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,50};
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 3, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,49};
yystate(48, [126|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 3, Tlen);
yystate(48, [61|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 3, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,48};
yystate(47, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 42, C =< 124 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(45, [108|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 9, Tlen);
yystate(45, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(45, [76|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 9, Tlen);
yystate(45, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,45};
yystate(44, [114|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,44};
yystate(43, [98|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, [97|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,43};
yystate(42, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,42};
yystate(41, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,41};
yystate(40, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(40, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(40, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(40, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(40, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 45 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(40, [C|Ics], Line, Tlen, Action, Alen) when C >= 47 ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(40, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,40};
yystate(39, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 42, C =< 45 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 47, C =< 126 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,38};
yystate(37, [115|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [83|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 82 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,37};
yystate(36, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 1, Tlen);
yystate(36, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 1, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 1, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 1, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 1, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,36};
yystate(35, [109|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,35};
yystate(34, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(33, Ics, Line, Tlen+1, 11, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,33};
yystate(32, [34|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 10, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,32};
yystate(31, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 42, C =< 47 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 91, C =< 96 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 123, C =< 126 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,31};
yystate(30, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(29, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,29};
yystate(28, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,28};
yystate(27, [97|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,27};
yystate(26, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,26};
yystate(25, [105|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, [101|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 104 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,25};
yystate(24, [46|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 21, Tlen);
yystate(24, [34|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 21, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(40, Ics, Line, Tlen+1, 21, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(40, Ics, Line, Tlen+1, 21, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 45 ->
    yystate(40, Ics, Line, Tlen+1, 21, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 47 ->
    yystate(40, Ics, Line, Tlen+1, 21, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line,24};
yystate(23, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(22, [61|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 3, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,22};
yystate(21, [119|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(21, [115|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(21, [109|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 12, Tlen);
yystate(21, [104|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(21, [100|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(21, [46|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 12, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Tlen+1, 12, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,21};
yystate(20, [114|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [82|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,20};
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 3, Tlen);
yystate(19, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 3, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 3, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 3, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 3, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,19};
yystate(18, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,18};
yystate(17, [118|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 117 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 119, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,17};
yystate(16, [37|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 19, Tlen);
yystate(16, [10|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line+1, Tlen+1, 19, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(16, Ics, Line, Tlen+1, 19, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(16, Ics, Line, Tlen+1, 19, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 36 ->
    yystate(16, Ics, Line, Tlen+1, 19, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 38 ->
    yystate(16, Ics, Line, Tlen+1, 19, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,16};
yystate(15, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(14, [126|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 18, Tlen);
yystate(14, [61|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 18, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,14};
yystate(13, [119|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [115|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [109|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [104|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [100|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [48|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [46|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 49, C =< 57 ->
    yystate(13, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,13};
yystate(12, [117|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [85|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,12};
yystate(11, [109|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,11};
yystate(10, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(10, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,10};
yystate(9, [102|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,9};
yystate(8, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 42, C =< 126 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(6, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(5, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(4, [101|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [69|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,4};
yystate(3, [101|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,3};
yystate(2, [115|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 8, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,2};
yystate(1, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 2, Tlen);
yystate(1, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 2, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 2, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,1};
yystate(0, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 42, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 91, C =< 94 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 123, C =< 125 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, _, _, _) ->
    yyaction_19();
yyaction(20, _, _, _) ->
    yyaction_20();
yyaction(21, _, _, _) ->
    yyaction_21();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 25).
yyaction_0(TokenChars, TokenLine) ->
     { token, { 'if', TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_1/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 26).
yyaction_1(TokenChars, TokenLine) ->
     { token, { var, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_2/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 27).
yyaction_2(TokenChars, TokenLine) ->
     { token, { def, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_3/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 28).
yyaction_3(TokenChars, TokenLine) ->
     { token, { operator, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_4/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 29).
yyaction_4(TokenChars, TokenLine) ->
     { token, { stream_id, TokenLine, list_to_binary (TokenChars) } } .

-compile({inline,yyaction_5/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 30).
yyaction_5(TokenChars, TokenLine) ->
     { token, { lambda, TokenLine, list_to_binary (lists : sublist (TokenChars, 9, length (TokenChars))) } } .

-compile({inline,yyaction_6/1}).
-file("apps/dfs/src/dfs_lexer.xrl", 31).
yyaction_6(TokenLine) ->
     { token, { user_node, TokenLine, user_node } } .

-compile({inline,yyaction_7/1}).
-file("apps/dfs/src/dfs_lexer.xrl", 32).
yyaction_7(TokenLine) ->
     { token, { node, TokenLine, node } } .

-compile({inline,yyaction_8/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 33).
yyaction_8(TokenChars, TokenLine) ->
     { token, { duration, TokenLine, TokenChars } } .

-compile({inline,yyaction_9/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 34).
yyaction_9(TokenChars, TokenLine) ->
     { token, { identifier, TokenLine, list_to_binary (TokenChars) } } .

-compile({inline,yyaction_10/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 35).
yyaction_10(TokenChars, TokenLine) ->
     { token, { reference, TokenLine, unquote (TokenChars) } } .

-compile({inline,yyaction_11/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 37).
yyaction_11(TokenChars, TokenLine) ->
     { token, { float, TokenLine, list_to_float (TokenChars) } } .

-compile({inline,yyaction_12/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 38).
yyaction_12(TokenChars, TokenLine) ->
     { token, { int, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_13/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 39).
yyaction_13(TokenChars, TokenLine) ->
     { token, { string, TokenLine, list_to_binary (strip (TokenChars, length (TokenChars))) } } .

-compile({inline,yyaction_14/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 40).
yyaction_14(TokenChars, TokenLine) ->
     { token, { text, TokenLine, list_to_binary (strip (TokenChars, length (TokenChars))) } } .

-compile({inline,yyaction_15/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 41).
yyaction_15(TokenChars, TokenLine) ->
     { token, { regex, TokenLine, prep_regex (TokenChars) } } .

-compile({inline,yyaction_16/1}).
-file("apps/dfs/src/dfs_lexer.xrl", 42).
yyaction_16(TokenLine) ->
     { token, { bool, TokenLine, true } } .

-compile({inline,yyaction_17/1}).
-file("apps/dfs/src/dfs_lexer.xrl", 43).
yyaction_17(TokenLine) ->
     { token, { bool, TokenLine, false } } .

-compile({inline,yyaction_18/2}).
-file("apps/dfs/src/dfs_lexer.xrl", 45).
yyaction_18(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_19/0}).
-file("apps/dfs/src/dfs_lexer.xrl", 46).
yyaction_19() ->
     skip_token .

-compile({inline,yyaction_20/0}).
-file("apps/dfs/src/dfs_lexer.xrl", 47).
yyaction_20() ->
     skip_token .

-compile({inline,yyaction_21/0}).
-file("apps/dfs/src/dfs_lexer.xrl", 48).
yyaction_21() ->
     skip_token .

-file("/opt/erlang/19_1/lib/parsetools-2.1.3/include/leexinc.hrl", 290).
