-file("/home/heyoka/.asdf/installs/erlang/23.2.3/lib/parsetools-2.2/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(dfs_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/dfs_lexer.xrl", 53).

-export([reserved_word/1]).

reserved_word('def') -> true.
strip_text(TokenChars,TokenLen) -> string:trim(lists:sublist(TokenChars, 4, TokenLen - 6)).
strip(TokenChars,TokenLen) -> lists:sublist(TokenChars, 2, TokenLen - 2).
%strip_ref(TokenChars,TokenLen) -> lists:sublist(TokenChars, 3, TokenLen - 3).
unquote(TokenChars) -> binary:replace(list_to_binary(TokenChars),<<"\"">>, <<>>, [global]).
prep_regex(TokenChars) -> binary:replace(list_to_binary(TokenChars),<<"?">>, <<>>, [global]).
-file("/home/heyoka/.asdf/installs/erlang/23.2.3/lib/parsetools-2.2/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/dfs_lexer.erl", 316).
yystate() -> 73.

yystate(80, [48|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 1, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 49, C =< 57 ->
    yystate(76, Ics, Line, Tlen+1, 1, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,80};
yystate(79, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(78, [115|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [83|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 82 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,78};
yystate(77, [37|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 20, Tlen);
yystate(77, [10|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line+1, Tlen+1, 20, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(77, Ics, Line, Tlen+1, 20, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(77, Ics, Line, Tlen+1, 20, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 36 ->
    yystate(77, Ics, Line, Tlen+1, 20, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 38 ->
    yystate(77, Ics, Line, Tlen+1, 20, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,77};
yystate(76, [119|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 12, Tlen);
yystate(76, [115|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 12, Tlen);
yystate(76, [109|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 12, Tlen);
yystate(76, [104|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 12, Tlen);
yystate(76, [100|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 12, Tlen);
yystate(76, [48|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 12, Tlen);
yystate(76, [46|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 12, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 49, C =< 57 ->
    yystate(76, Ics, Line, Tlen+1, 12, Tlen);
yystate(76, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,76};
yystate(75, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(75, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(75, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,75};
yystate(74, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(73, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [70|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line+1, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 32 ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 99 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 107 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 109, C =< 113 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 117, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,73};
yystate(72, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [58|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,72};
yystate(71, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(71, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,71};
yystate(70, [108|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [76|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,70};
yystate(69, [37|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 20, Tlen);
yystate(69, [10|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line+1, Tlen+1, 20, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(69, Ics, Line, Tlen+1, 20, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(69, Ics, Line, Tlen+1, 20, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,69};
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(68, Ics, Line, Tlen+1, 11, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,68};
yystate(67, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(66, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 47 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 91 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 123 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(66, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,66};
yystate(65, [124|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 6, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,65};
yystate(64, [32|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 4, Tlen);
yystate(64, [10|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line+1, Tlen+1, 4, Tlen);
yystate(64, [9|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 4, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,64};
yystate(63, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(63, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,63};
yystate(62, [97|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [65|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,62};
yystate(61, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(60, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [61|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 1, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,59};
yystate(58, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 45 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 47, C =< 58 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 91 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 123 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(56, [105|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [101|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 104 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,56};
yystate(55, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(54, [32|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 3, Tlen);
yystate(54, [10|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line+1, Tlen+1, 3, Tlen);
yystate(54, [9|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 3, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,54};
yystate(53, [126|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 1, Tlen);
yystate(53, [61|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 1, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,53};
yystate(52, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(51, [126|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 18, Tlen);
yystate(51, [61|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 18, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,51};
yystate(50, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 47 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 91 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 123 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(50, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,50};
yystate(49, [114|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [82|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,49};
yystate(48, [118|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 117 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 119, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,48};
yystate(47, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [58|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,46};
yystate(45, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 45 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 47 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, [115|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 8, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,44};
yystate(43, [61|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 1, Tlen);
yystate(43, [60|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,43};
yystate(42, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 58 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 91 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,42};
yystate(41, [117|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 9, Tlen);
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(41, [85|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 9, Tlen);
yystate(41, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,41};
yystate(40, [102|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,40};
yystate(39, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, [97|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 9, Tlen);
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(38, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,38};
yystate(37, [34|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 10, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,37};
yystate(36, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line+1, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 61 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 63 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(36, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,36};
yystate(35, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,35};
yystate(34, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [51|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 50 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 52, C =< 58 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 91 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 123 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,34};
yystate(33, [101|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [69|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,33};
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 0, Tlen);
yystate(32, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 0, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 0, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 0, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 0, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,32};
yystate(31, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,31};
yystate(30, [100|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,30};
yystate(29, [46|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 21, Tlen);
yystate(29, [34|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 21, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(45, Ics, Line, Tlen+1, 21, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(45, Ics, Line, Tlen+1, 21, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 45 ->
    yystate(45, Ics, Line, Tlen+1, 21, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 47 ->
    yystate(45, Ics, Line, Tlen+1, 21, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line,29};
yystate(28, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line+1, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 61 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 63 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,28};
yystate(27, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line+1, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 8 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 31 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 33, C =< 45 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 47, C =< 59 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 61 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 58 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 91 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 123 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,26};
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,25};
yystate(24, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(23, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,23};
yystate(22, [98|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 9, Tlen);
yystate(22, [97|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(22, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,22};
yystate(21, [37|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [10|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line+1, Tlen+1, 19, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(21, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(21, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 36 ->
    yystate(21, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 38 ->
    yystate(21, Ics, Line, Tlen+1, 19, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,21};
yystate(20, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line+1, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 61 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 63 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(20, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,20};
yystate(19, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line+1, Tlen+1, Action, Alen);
yystate(19, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line+1, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 59 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(19, [C|Ics], Line, Tlen, Action, Alen) when C >= 63 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(19, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,19};
yystate(18, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 45 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 47, C =< 58 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 91 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 123 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,18};
yystate(17, [101|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,17};
yystate(16, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,16};
yystate(15, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, [109|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,14};
yystate(13, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 58 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 91 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 123 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line+1, Tlen+1, Action, Alen);
yystate(12, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line+1, Tlen+1, Action, Alen);
yystate(12, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 59 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(12, [C|Ics], Line, Tlen, Action, Alen) when C >= 63 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(12, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,12};
yystate(11, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(11, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,11};
yystate(10, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 47 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 62 ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(10, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,10};
yystate(9, [109|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,9};
yystate(8, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(6, [97|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 9, Tlen);
yystate(6, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(6, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 9, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,6};
yystate(5, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(4, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(3, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(1, [95|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 1, Tlen);
yystate(1, [46|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 1, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 1, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(25, Ics, Line, Tlen+1, 1, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(25, Ics, Line, Tlen+1, 1, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,1};
yystate(0, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, _, _, _) ->
    yyaction_19();
yyaction(20, _, _, _) ->
    yyaction_20();
yyaction(21, _, _, _) ->
    yyaction_21();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("src/dfs_lexer.xrl", 26).
yyaction_0(TokenChars, TokenLine) ->
     { token, { def, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_1/2}).
-file("src/dfs_lexer.xrl", 27).
yyaction_1(TokenChars, TokenLine) ->
     { token, { operator, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_2/2}).
-file("src/dfs_lexer.xrl", 28).
yyaction_2(TokenChars, TokenLine) ->
     { token, { stream_id, TokenLine, list_to_binary (TokenChars) } } .

-compile({inline,yyaction_3/2}).
-file("src/dfs_lexer.xrl", 29).
yyaction_3(TokenChars, TokenLine) ->
     { token, { lambda, TokenLine, list_to_binary (lists : sublist (TokenChars, 9, length (TokenChars))) } } .

-compile({inline,yyaction_4/2}).
-file("src/dfs_lexer.xrl", 30).
yyaction_4(TokenChars, TokenLine) ->
     { token, { inline, TokenLine, list_to_binary (lists : sublist (TokenChars, 3, length (TokenChars))) } } .

-compile({inline,yyaction_5/1}).
-file("src/dfs_lexer.xrl", 31).
yyaction_5(TokenLine) ->
     { token, { user_node, TokenLine, user_node } } .

-compile({inline,yyaction_6/1}).
-file("src/dfs_lexer.xrl", 32).
yyaction_6(TokenLine) ->
     { token, { node, TokenLine, node } } .

-compile({inline,yyaction_7/1}).
-file("src/dfs_lexer.xrl", 33).
yyaction_7(TokenLine) ->
     { token, { macro, TokenLine, macro } } .

-compile({inline,yyaction_8/2}).
-file("src/dfs_lexer.xrl", 34).
yyaction_8(TokenChars, TokenLine) ->
     { token, { duration, TokenLine, list_to_binary (TokenChars) } } .

-compile({inline,yyaction_9/2}).
-file("src/dfs_lexer.xrl", 35).
yyaction_9(TokenChars, TokenLine) ->
     { token, { identifier, TokenLine, list_to_binary (TokenChars) } } .

-compile({inline,yyaction_10/2}).
-file("src/dfs_lexer.xrl", 36).
yyaction_10(TokenChars, TokenLine) ->
     { token, { reference, TokenLine, unquote (TokenChars) } } .

-compile({inline,yyaction_11/2}).
-file("src/dfs_lexer.xrl", 38).
yyaction_11(TokenChars, TokenLine) ->
     { token, { float, TokenLine, list_to_float (TokenChars) } } .

-compile({inline,yyaction_12/2}).
-file("src/dfs_lexer.xrl", 39).
yyaction_12(TokenChars, TokenLine) ->
     { token, { int, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_13/2}).
-file("src/dfs_lexer.xrl", 40).
yyaction_13(TokenChars, TokenLine) ->
     { token, { text, TokenLine, list_to_binary (strip_text (TokenChars, length (TokenChars))) } } .

-compile({inline,yyaction_14/2}).
-file("src/dfs_lexer.xrl", 41).
yyaction_14(TokenChars, TokenLine) ->
     { token, { string, TokenLine, list_to_binary (strip (TokenChars, length (TokenChars))) } } .

-compile({inline,yyaction_15/2}).
-file("src/dfs_lexer.xrl", 42).
yyaction_15(TokenChars, TokenLine) ->
     { token, { regex, TokenLine, prep_regex (TokenChars) } } .

-compile({inline,yyaction_16/1}).
-file("src/dfs_lexer.xrl", 43).
yyaction_16(TokenLine) ->
     { token, { bool, TokenLine, true } } .

-compile({inline,yyaction_17/1}).
-file("src/dfs_lexer.xrl", 44).
yyaction_17(TokenLine) ->
     { token, { bool, TokenLine, false } } .

-compile({inline,yyaction_18/2}).
-file("src/dfs_lexer.xrl", 46).
yyaction_18(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_19/0}).
-file("src/dfs_lexer.xrl", 47).
yyaction_19() ->
     skip_token .

-compile({inline,yyaction_20/0}).
-file("src/dfs_lexer.xrl", 48).
yyaction_20() ->
     skip_token .

-compile({inline,yyaction_21/0}).
-file("src/dfs_lexer.xrl", 49).
yyaction_21() ->
     skip_token .

-file("/home/heyoka/.asdf/installs/erlang/23.2.3/lib/parsetools-2.2/include/leexinc.hrl", 313).
